# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.CharField(max_length=50)),
                ('playing_time', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('links', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanisms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='mechanisms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game.Mechanisms'),
        ),
        migrations.AddField(
            model_name='games',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game.Type'),
        ),
    ]
